AllCops:
  TargetRubyVersion: 2.4

Metrics:
  Enabled: false

# Broken due to ruby version checks in Gemfile
Bundler/DuplicatedGem:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
